if (DEFINED QT6_CMAKE_ROOT)
    list(APPEND CMAKE_PREFIX_PATH ${QT6_CMAKE_ROOT})
elseif(DEFINED ENV{QT6_CMAKE_ROOT})
    list(APPEND CMAKE_PREFIX_PATH $ENV{QT6_CMAKE_ROOT})
else()
    message(FATAL_ERROR "A environment variable or a cmake parameter named QT6_CMAKE_ROOT should be specified as 'path/to/Qt6/lib/cmake/Qt6'.")
endif()